# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GifApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Gifu'
  # Pods for GifApp

  target 'GifAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
